name: In-Out test

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - run: make
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
        
      - name: generate tests with one param
        run: sudo python3 tests/test_1param.py
      - name: generate tests with two param
        run: sudo python3 tests/test_2param.py
