name: pushdocs.yml

on:
  push:	
    branches:	
      - master
      - gh-pages

jobs:

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    
    - run: sudo apt-get install doxygen
    - run: sudo apt-get install graphviz
    - run: doxygen doxconf

    - name: Make pdf  
      run: |
        sudo apt install texlive-latex-extra
        cd DOCS/latex
        make
    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: DOCS/latex/refman.pdf

    - name: Push git subdirectory as branch
      uses: s0/git-publish-subdir-action@v2.4.0

      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: DOCS/html
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}